import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

export type Language = "pt" | "en" | "es";

type TranslationKey = string;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// UI translations for all 3 languages
const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Nav
    "nav.home": "Início",
    "nav.itineraries": "Roteiros",
    "nav.waterfalls": "Cachoeiras",
    "nav.experiences": "Experiências",
    "nav.accommodations": "Hospedagens",
    "nav.services": "Serviços",
    "nav.immersions": "Imersões",
    "nav.faq": "Dúvidas",
    "nav.wishlist": "Preferências",
    "nav.buildItinerary": "Monte seu Roteiro",
    // Hero
    "hero.tagline": "Curadoria de Experiências na Chapada dos Veadeiros",
    "hero.subtitle": "Reconecte-se com a natureza através de vivências autênticas guiadas por quem conhece cada trilha, cachoeira e pôr do sol.",
    "hero.cta": "Roteiros Prontos",
    "hero.cta2": "Monte seu Roteiro",
    // Paths
    "paths.title": "Como você quer viver a Chapada?",
    "paths.ready.title": "Roteiro Pronto",
    "paths.ready.desc": "Escolha um pacote completo de 2 a 5 dias. Roteiros curados com os melhores atrativos, transporte 4x4, guia especialista e tudo pensado nos mínimos detalhes.",
    "paths.ready.cta": "Ver Roteiros Prontos",
    "paths.ready.bullet1": "Pacotes de 2 a 5 dias",
    "paths.ready.bullet2": "Clássico ou Jurássico",
    "paths.ready.bullet3": "Tudo incluído",
    "paths.custom.title": "Monte seu Roteiro",
    "paths.custom.desc": "Crie sua experiência sob medida. Escolha cachoeiras, experiências, hospedagem e serviços — e receba um orçamento personalizado via WhatsApp.",
    "paths.custom.cta": "Começar a Montar",
    "paths.custom.bullet1": "Escolha suas cachoeiras",
    "paths.custom.bullet2": "Adicione experiências",
    "paths.custom.bullet3": "Selecione hospedagem e serviços",
    // About
    "about.title": "O que é a ATMOS?",
    "about.text1": "A ATMOS é uma curadoria de experiências imersivas na Chapada dos Veadeiros. Não somos uma agência — somos um convite para viver a Chapada de forma autêntica, profunda e transformadora.",
    "about.text2": "Cada roteiro é desenhado para conectar você à essência do Cerrado: suas cachoeiras escondidas, seus cânions milenares, sua energia única.",
    // Categories
    "categories.title": "Explore por Categoria",
    "categories.subtitle": "Navegue pelos pilares da sua viagem e monte a experiência perfeita na Chapada dos Veadeiros.",
    "categories.itineraries": "Roteiros Prontos",
    "categories.itineraries.desc": "Pacotes de 2 a 5 dias com tudo incluído",
    "categories.waterfalls": "Cachoeiras",
    "categories.waterfalls.desc": "Mais de 35 atrativos naturais para explorar",
    "categories.experiences": "Experiências",
    "categories.experiences.desc": "17 vivências únicas curadas pela ATMOS",
    "categories.accommodations": "Hospedagens",
    "categories.accommodations.desc": "30+ propriedades selecionadas a dedo",
    "categories.services": "Serviços",
    "categories.services.desc": "Drone, lanches de trilha, transfer e mais",
    // Guide
    "guide.title": "Sobre João Accioly",
    "guide.text1": "Guia bilíngue há quase 10 anos na Chapada dos Veadeiros, é quem nos abre as trilhas, os segredos e os encantos da região, com profundo respeito pela terra, pelos saberes locais e pela segurança do grupo.",
    "guide.text2": "Sua missão é mostrar a Chapada que poucos conhecem, os acessos secretos, os horários mágicos, os ângulos perfeitos. Cada detalhe é pensado para criar memórias que duram uma vida.",
    // CTA
    "cta.title": "Pronto para viver a Chapada?",
    "cta.subtitle": "Monte sua wishlist com roteiros, cachoeiras, experiências e hospedagens — e receba um orçamento personalizado.",
    "cta.button": "Montar Minhas Preferências",
    "cta.button2": "Ver Roteiros Prontos",
    // Footer
    "footer.tagline": "Curadoria de Experiências na Chapada dos Veadeiros",
    "footer.contact": "Contato",
    "footer.follow": "Siga-nos",
    "footer.rights": "Todos os direitos reservados.",
    // Wishlist
    "wishlist.title": "Minhas Preferências",
    "wishlist.empty": "Seu roteiro ideal começa aqui. Salve o que te interessa e nossa equipe fará o resto.",
    "wishlist.items": "itens",
    "wishlist.send": "Enviar Orçamento via WhatsApp",
    "wishlist.floating": "Preferências",
    // Auth
    "auth.modal.title": "Salve suas Preferências",
    "auth.modal.subtitle": "Crie sua conta gratuita para salvar seus favoritos e receber um roteiro de curadoria única.",
    "auth.tab.signup": "Criar conta",
    "auth.tab.signin": "Entrar",
    "auth.field.name": "Nome completo",
    "auth.field.phone": "Telefone com DDD",
    "auth.field.email": "E-mail",
    "auth.field.password": "Senha",
    "auth.placeholder.name": "João Silva",
    "auth.placeholder.password": "Mínimo 6 caracteres",
    "auth.hint.password": "Mínimo de 6 caracteres",
    "auth.noAccount": "Não tem conta?",
    "auth.loading": "Aguarde...",
    "auth.signout": "Sair",
    "auth.signin.header": "Entrar",
    "auth.confirm.title": "Verifique seu e-mail",
    "auth.confirm.message": "Enviamos um link de confirmação para",
    "auth.confirm.goto": "Ir para o login",
    "auth.error.required": "Preencha todos os campos",
    "auth.error.email": "E-mail inválido",
    "auth.error.password": "Senha deve ter ao menos 6 caracteres",
    "auth.error.phone": "Telefone inválido — informe DDD + número",
    "auth.error.credentials": "E-mail ou senha incorretos",
    "auth.error.emailFormat": "Insira um e-mail válido (ex: nome@dominio.com)",
    "auth.error.passwordMatch": "As senhas não coincidem",
    "auth.field.confirmPassword": "Confirme sua senha",
    "auth.forgotPassword": "Esqueci minha senha",
    "auth.forgot.title": "Recuperar senha",
    "auth.forgot.subtitle": "Enviaremos um link para você redefinir sua senha.",
    "auth.forgot.send": "Enviar link",
    "auth.forgot.sent": "Link enviado! Verifique seu e-mail.",
    "auth.forgot.back": "Voltar ao login",
    "auth.reset.title": "Nova senha",
    "auth.reset.subtitle": "Digite sua nova senha abaixo.",
    "auth.reset.field": "Nova senha",
    "auth.reset.confirm": "Confirmar nova senha",
    "auth.reset.save": "Salvar nova senha",
    "auth.reset.success": "Senha alterada com sucesso!",
    "auth.reset.error.match": "As senhas não coincidem",
    "auth.reset.error.min": "Senha deve ter ao menos 6 caracteres",
    "auth.reset.goto": "Ir para a página inicial",
    // Profile
    "profile.title": "Meu Perfil",
    "profile.back": "Voltar",
    "profile.language": "Idioma preferido",
    "profile.save": "Salvar alterações",
    "profile.saved": "Alterações salvas com sucesso!",
    "profile.error.save": "Erro ao salvar. Tente novamente.",
    "nav.profile": "Meu Perfil",
    // How it works
    "howitworks.title": "Como funcionam as Preferências ATMOS?",
    "howitworks.subtitle": "Monte sua viagem dos sonhos em três passos simples.",
    "howitworks.step1.title": "Explore",
    "howitworks.step1.desc": "Navegue por cachoeiras, experiências, hospedagens e serviços curados pela ATMOS.",
    "howitworks.step2.title": "Favorite",
    "howitworks.step2.desc": "Clique no coração para salvar nas suas Preferências tudo que te interessa.",
    "howitworks.step3.title": "Solicite seu Orçamento",
    "howitworks.step3.desc": "Com suas Preferências prontas, solicite um orçamento. Nossa equipe vai analisar suas escolhas e montar o roteiro ideal.",
    "howitworks.cta": "Começar a explorar",
    // Floating wishlist
    "wishlist.floating.empty": "Monte suas Preferências",
    "wishlist.floating.tooltip": "Adicione cachoeiras, experiências e hospedagens para receber um orçamento personalizado",
  },
  en: {
    "nav.home": "Home",
    "nav.itineraries": "Itineraries",
    "nav.waterfalls": "Waterfalls",
    "nav.experiences": "Experiences",
    "nav.accommodations": "Stays",
    "nav.services": "Services",
    "nav.immersions": "Immersions",
    "nav.faq": "FAQ",
    "nav.wishlist": "Preferences",
    "nav.buildItinerary": "Build Your Own",
    "hero.tagline": "Curated Experiences in Chapada dos Veadeiros",
    "hero.subtitle": "Reconnect with nature through authentic experiences guided by someone who knows every trail, waterfall and sunset.",
    "hero.cta": "Ready-Made Itineraries",
    "hero.cta2": "Build Your Own",
    "paths.title": "How do you want to experience the Chapada?",
    "paths.ready.title": "Ready-Made Itinerary",
    "paths.ready.desc": "Choose a complete 2 to 5-day package. Curated itineraries with the best attractions, 4x4 transport, expert guide and every detail planned.",
    "paths.ready.cta": "See Itineraries",
    "paths.ready.bullet1": "2 to 5-day packages",
    "paths.ready.bullet2": "Classic or Jurassic",
    "paths.ready.bullet3": "All-inclusive",
    "paths.custom.title": "Build Your Own",
    "paths.custom.desc": "Create your tailor-made experience. Choose waterfalls, experiences, accommodation and services — and receive a personalized quote via WhatsApp.",
    "paths.custom.cta": "Start Building",
    "paths.custom.bullet1": "Choose your waterfalls",
    "paths.custom.bullet2": "Add experiences",
    "paths.custom.bullet3": "Select stays and services",
    "about.title": "What is ATMOS?",
    "about.text1": "ATMOS is a curation of immersive experiences in Chapada dos Veadeiros. We're not an agency — we're an invitation to live the Chapada authentically, deeply and transformatively.",
    "about.text2": "Each itinerary is designed to connect you with the essence of the Cerrado: its hidden waterfalls, ancient canyons, and unique energy.",
    "categories.title": "Explore by Category",
    "categories.subtitle": "Browse the pillars of your trip and build the perfect experience in Chapada dos Veadeiros.",
    "categories.itineraries": "Ready-Made Itineraries",
    "categories.itineraries.desc": "2 to 5-day all-inclusive packages",
    "categories.waterfalls": "Waterfalls",
    "categories.waterfalls.desc": "35+ natural attractions to explore",
    "categories.experiences": "Experiences",
    "categories.experiences.desc": "17 unique experiences curated by ATMOS",
    "categories.accommodations": "Stays",
    "categories.accommodations.desc": "30+ hand-picked properties",
    "categories.services": "Services",
    "categories.services.desc": "Drone, trail snacks, transfers and more",
    "guide.title": "About João Accioly",
    "guide.text1": "Bilingual guide for nearly 10 years in Chapada dos Veadeiros, he opens the trails, secrets and wonders of the region for us, with deep respect for the land, local knowledge and the group's safety.",
    "guide.text2": "His mission is to show the Chapada few people know — the secret paths, the magical hours, the perfect angles. Every detail is crafted to create memories that last a lifetime.",
    "cta.title": "Ready to experience the Chapada?",
    "cta.subtitle": "Build your wishlist with itineraries, waterfalls, experiences and stays — and receive a personalized quote.",
    "cta.button": "Build My Preferences",
    "cta.button2": "See Itineraries",
    "footer.tagline": "Curated Experiences in Chapada dos Veadeiros",
    "footer.contact": "Contact",
    "footer.follow": "Follow Us",
    "footer.rights": "All rights reserved.",
    "wishlist.title": "My Preferences",
    "wishlist.empty": "Save what interests you. Our team analyzes everything and builds the ideal itinerary for you.",
    "wishlist.items": "items",
    "wishlist.send": "Send Quote via WhatsApp",
    "wishlist.floating": "Preferences",
    // Auth
    "auth.modal.title": "Save Your Preferences",
    "auth.modal.subtitle": "Create your account to save your favorites and receive a unique curated itinerary.",
    "auth.tab.signup": "Create account",
    "auth.tab.signin": "Sign in",
    "auth.field.name": "Full name",
    "auth.field.phone": "Phone with area code",
    "auth.field.email": "Email",
    "auth.field.password": "Password",
    "auth.placeholder.name": "John Smith",
    "auth.placeholder.password": "Minimum 6 characters",
    "auth.hint.password": "Minimum 6 characters",
    "auth.noAccount": "Don't have an account?",
    "auth.loading": "Please wait...",
    "auth.signout": "Sign out",
    "auth.signin.header": "Sign in",
    "auth.confirm.title": "Check your email",
    "auth.confirm.message": "We sent a confirmation link to",
    "auth.confirm.goto": "Go to sign in",
    "auth.error.required": "Please fill in all fields",
    "auth.error.email": "Invalid email address",
    "auth.error.password": "Password must be at least 6 characters",
    "auth.error.phone": "Invalid phone — include area code + number",
    "auth.error.credentials": "Incorrect email or password",
    "auth.error.emailFormat": "Enter a valid email (e.g. name@domain.com)",
    "auth.error.passwordMatch": "Passwords do not match",
    "auth.field.confirmPassword": "Confirm password",
    "auth.forgotPassword": "Forgot my password",
    "auth.forgot.title": "Reset password",
    "auth.forgot.subtitle": "We'll send you a link to reset your password.",
    "auth.forgot.send": "Send link",
    "auth.forgot.sent": "Link sent! Check your email.",
    "auth.forgot.back": "Back to sign in",
    "auth.reset.title": "New password",
    "auth.reset.subtitle": "Enter your new password below.",
    "auth.reset.field": "New password",
    "auth.reset.confirm": "Confirm new password",
    "auth.reset.save": "Save new password",
    "auth.reset.success": "Password updated successfully!",
    "auth.reset.error.match": "Passwords do not match",
    "auth.reset.error.min": "Password must be at least 6 characters",
    "auth.reset.goto": "Go to home page",
    // Profile
    "profile.title": "My Profile",
    "profile.back": "Back",
    "profile.language": "Preferred language",
    "profile.save": "Save changes",
    "profile.saved": "Changes saved successfully!",
    "profile.error.save": "Error saving. Please try again.",
    "nav.profile": "My Profile",
    // How it works
    "howitworks.title": "What are ATMOS Preferences?",
    "howitworks.subtitle": "Plan your dream trip in three simple steps.",
    "howitworks.step1.title": "Explore",
    "howitworks.step1.desc": "Browse waterfalls, experiences, stays and services curated by ATMOS.",
    "howitworks.step2.title": "Favorite",
    "howitworks.step2.desc": "Click the heart to save everything that interests you to your Wishlist.",
    "howitworks.step3.title": "Request a Quote",
    "howitworks.step3.desc": "Once your Wishlist is ready, request a quote. An ATMOS attendant will review your choices and get in touch to customize everything.",
    "howitworks.cta": "Start exploring",
    "wishlist.floating.empty": "Build your Preferences",
    "wishlist.floating.tooltip": "Add waterfalls, experiences and stays to get a personalized quote",
  },
  es: {
    "nav.home": "Inicio",
    "nav.itineraries": "Itinerarios",
    "nav.waterfalls": "Cascadas",
    "nav.experiences": "Experiencias",
    "nav.accommodations": "Hospedajes",
    "nav.services": "Servicios",
    "nav.immersions": "Inmersiones",
    "nav.faq": "Dudas",
    "nav.wishlist": "Preferencias",
    "nav.buildItinerary": "Arma tu Itinerario",
    "hero.tagline": "Curaduría de Experiencias en Chapada dos Veadeiros",
    "hero.subtitle": "Reconéctate con la naturaleza a través de vivencias auténticas guiadas por quien conoce cada sendero, cascada y atardecer.",
    "hero.cta": "Itinerarios Listos",
    "hero.cta2": "Arma tu Itinerario",
    "paths.title": "¿Cómo quieres vivir la Chapada?",
    "paths.ready.title": "Itinerario Listo",
    "paths.ready.desc": "Elige un paquete completo de 2 a 5 días. Itinerarios curados con los mejores atractivos, transporte 4x4, guía experto y todo planificado al detalle.",
    "paths.ready.cta": "Ver Itinerarios",
    "paths.ready.bullet1": "Paquetes de 2 a 5 días",
    "paths.ready.bullet2": "Clásico o Jurásico",
    "paths.ready.bullet3": "Todo incluido",
    "paths.custom.title": "Arma tu Itinerario",
    "paths.custom.desc": "Crea tu experiencia a medida. Elige cascadas, experiencias, hospedaje y servicios — y recibe un presupuesto personalizado por WhatsApp.",
    "paths.custom.cta": "Empezar a Armar",
    "paths.custom.bullet1": "Elige tus cascadas",
    "paths.custom.bullet2": "Agrega experiencias",
    "paths.custom.bullet3": "Selecciona hospedaje y servicios",
    "about.title": "¿Qué es ATMOS?",
    "about.text1": "ATMOS es una curaduría de experiencias inmersivas en Chapada dos Veadeiros. No somos una agencia — somos una invitación a vivir la Chapada de forma auténtica, profunda y transformadora.",
    "about.text2": "Cada itinerario está diseñado para conectarte con la esencia del Cerrado: sus cascadas escondidas, sus cañones milenarios, su energía única.",
    "categories.title": "Explora por Categoría",
    "categories.subtitle": "Navega por los pilares de tu viaje y arma la experiencia perfecta en Chapada dos Veadeiros.",
    "categories.itineraries": "Itinerarios Listos",
    "categories.itineraries.desc": "Paquetes de 2 a 5 días todo incluido",
    "categories.waterfalls": "Cascadas",
    "categories.waterfalls.desc": "Más de 35 atractivos naturales",
    "categories.experiences": "Experiencias",
    "categories.experiences.desc": "17 vivencias únicas curadas por ATMOS",
    "categories.accommodations": "Hospedajes",
    "categories.accommodations.desc": "30+ propiedades seleccionadas",
    "categories.services": "Servicios",
    "categories.services.desc": "Drone, snacks de sendero, transfer y más",
    "guide.title": "Sobre João Accioly",
    "guide.text1": "Guía bilingüe desde hace casi 10 años en Chapada dos Veadeiros, es quien nos abre los senderos, los secretos y los encantos de la región, con profundo respeto por la tierra, los saberes locales y la seguridad del grupo.",
    "guide.text2": "Su misión es mostrar la Chapada que pocos conocen — los accesos secretos, las horas mágicas, los ángulos perfectos. Cada detalle está pensado para crear recuerdos que duran toda la vida.",
    "cta.title": "¿Listo para vivir la Chapada?",
    "cta.subtitle": "Arma tu wishlist con itinerarios, cascadas, experiencias y hospedajes — y recibe un presupuesto personalizado.",
    "cta.button": "Armar Mis Preferencias",
    "cta.button2": "Ver Itinerarios",
    "footer.tagline": "Curaduría de Experiencias en Chapada dos Veadeiros",
    "footer.contact": "Contacto",
    "footer.follow": "Síguenos",
    "footer.rights": "Todos los derechos reservados.",
    "wishlist.title": "Mis Preferencias",
    "wishlist.empty": "Guarda lo que te interesa. Nuestro equipo analiza todo y arma el itinerario ideal para ti.",
    "wishlist.items": "ítems",
    "wishlist.send": "Enviar Presupuesto por WhatsApp",
    "wishlist.floating": "Preferencias",
    // Auth
    "auth.modal.title": "Guarda tus Preferencias",
    "auth.modal.subtitle": "Crea tu cuenta para guardar tus favoritos y recibir un itinerario de curaduría única.",
    "auth.tab.signup": "Crear cuenta",
    "auth.tab.signin": "Entrar",
    "auth.field.name": "Nombre completo",
    "auth.field.phone": "Teléfono con código de área",
    "auth.field.email": "Correo electrónico",
    "auth.field.password": "Contraseña",
    "auth.placeholder.name": "Juan García",
    "auth.placeholder.password": "Mínimo 6 caracteres",
    "auth.hint.password": "Mínimo 6 caracteres",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.loading": "Por favor espera...",
    "auth.signout": "Salir",
    "auth.signin.header": "Entrar",
    "auth.confirm.title": "Revisa tu correo",
    "auth.confirm.message": "Enviamos un enlace de confirmación a",
    "auth.confirm.goto": "Ir a iniciar sesión",
    "auth.error.required": "Por favor completa todos los campos",
    "auth.error.email": "Correo electrónico inválido",
    "auth.error.password": "La contraseña debe tener al menos 6 caracteres",
    "auth.error.phone": "Teléfono inválido — incluye código de área + número",
    "auth.error.credentials": "Correo o contraseña incorrectos",
    "auth.error.emailFormat": "Ingresa un email válido (ej: nombre@dominio.com)",
    "auth.error.passwordMatch": "Las contraseñas no coinciden",
    "auth.field.confirmPassword": "Confirma tu contraseña",
    "auth.forgotPassword": "Olvidé mi contraseña",
    "auth.forgot.title": "Recuperar contraseña",
    "auth.forgot.subtitle": "Te enviaremos un enlace para restablecer tu contraseña.",
    "auth.forgot.send": "Enviar enlace",
    "auth.forgot.sent": "¡Enlace enviado! Revisa tu correo.",
    "auth.forgot.back": "Volver al inicio de sesión",
    "auth.reset.title": "Nueva contraseña",
    "auth.reset.subtitle": "Ingresa tu nueva contraseña abajo.",
    "auth.reset.field": "Nueva contraseña",
    "auth.reset.confirm": "Confirmar nueva contraseña",
    "auth.reset.save": "Guardar nueva contraseña",
    "auth.reset.success": "¡Contraseña actualizada con éxito!",
    "auth.reset.error.match": "Las contraseñas no coinciden",
    "auth.reset.error.min": "La contraseña debe tener al menos 6 caracteres",
    "auth.reset.goto": "Ir a la página de inicio",
    // Profile
    "profile.title": "Mi Perfil",
    "profile.back": "Volver",
    "profile.language": "Idioma preferido",
    "profile.save": "Guardar cambios",
    "profile.saved": "¡Cambios guardados con éxito!",
    "profile.error.save": "Error al guardar. Inténtalo de nuevo.",
    "nav.profile": "Mi Perfil",
    // How it works
    "howitworks.title": "¿Qué son las Preferencias ATMOS?",
    "howitworks.subtitle": "Arma tu viaje soñado en tres pasos simples.",
    "howitworks.step1.title": "Explora",
    "howitworks.step1.desc": "Navega por cascadas, experiencias, hospedajes y servicios curados por ATMOS.",
    "howitworks.step2.title": "Favorite",
    "howitworks.step2.desc": "Haz clic en el corazón para guardar en tus Preferencias todo lo que te interese.",
    "howitworks.step3.title": "Solicita tu Presupuesto",
    "howitworks.step3.desc": "Con tus Preferencias listas, solicita un presupuesto. Un asistente ATMOS analizará tus elecciones y te contactará para personalizar todo.",
    "howitworks.cta": "Empezar a explorar",
    "wishlist.floating.empty": "Arma tus Preferencias",
    "wishlist.floating.tooltip": "Agrega cascadas, experiencias y hospedajes para recibir un presupuesto personalizado",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("atmos-language");
    return (saved as Language) || "pt";
  });

  useEffect(() => {
    localStorage.setItem("atmos-language", language);
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const t = useCallback(
    (key: string) => {
      return translations[language][key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
